name: Docker workflows
run-name: Triggering test by ${{ github.actor }}

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build & run docker ${{ github.event_name }} on ${{ github.ref }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup pnpm@latest with Node.js
        uses: npm/action-setup@v2
        with:
          version: latest

      - name: Installing dependencies with `npm install`
        run: npm install
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/factonation:latest
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
      - name: Run the build process with Docker
        uses: docker://macgeargear/factonation
